#!/bin/sh
set -eu

PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
unset CDPATH ENV BASH_ENV PYTHONHOME PYTHONPATH PYTHONSTARTUP LD_LIBRARY_PATH LD_PRELOAD

host_env=${OWNER_PC_HOST_ENV:-/etc/codex-mobile/owner-pc-host.env}
image=/var/lib/codex-mobile-owner-pc/workspace-storage.xfs
mount_point=/srv/codex-mobile
expected_bytes=68719476736
coder_address=10.86.0.1

[ "$(id -u)" -eq 0 ] || {
  echo "owner-PC runtime preparation must run as root" >&2
  exit 1
}

# WSL interoperability shells run in a sibling mount namespace to systemd's
# PID 1. The persistent mount must always be created, verified, and removed in
# the namespace inherited by product services.
if [ -z "${INVOCATION_ID:-}" ]; then
  current_mount_namespace=$(readlink /proc/self/ns/mnt)
  service_mount_namespace=$(readlink /proc/1/ns/mnt)
  if [ "$current_mount_namespace" != "$service_mount_namespace" ]; then
    [ "${CODEX_MOBILE_PID1_MOUNT_NAMESPACE:-}" != 1 ] || {
      echo "cannot enter the systemd mount namespace" >&2
      exit 1
    }
    export CODEX_MOBILE_PID1_MOUNT_NAMESPACE=1
    exec nsenter --target 1 --mount -- /bin/sh "$0" "$@"
  fi
fi

[ -f "$host_env" ] && [ ! -L "$host_env" ] || {
  echo "$host_env must be an existing non-symlink file" >&2
  exit 1
}
[ "$(stat -c '%u:%g:%a' "$host_env")" = 0:0:600 ] || {
  echo "$host_env must be root:root with exact mode 0600" >&2
  exit 1
}

set -a
# The file is generated by the root-only setup script, has a fixed key set,
# and is validated again below before any value reaches a privileged command.
. "$host_env"
set +a

[ "${DEPLOYMENT_PROFILE:-}" = owner_pc_beta ] || {
  echo "owner-PC host configuration must select DEPLOYMENT_PROFILE=owner_pc_beta" >&2
  exit 1
}
[ "${DATA_ROOT:-}" = "$mount_point" ] || {
  echo "owner-PC DATA_ROOT must be $mount_point" >&2
  exit 1
}
[ "${OWNER_PC_STORAGE_IMAGE:-}" = "$image" ] || {
  echo "owner-PC storage image must be $image" >&2
  exit 1
}
[ "${OWNER_PC_STORAGE_GIB:-}" = 64 ] || {
  echo "owner-PC storage image must be exactly 64 GiB" >&2
  exit 1
}
[ "${CODER_BIND_ADDRESS:-}" = "$coder_address" ] || {
  echo "owner-PC Coder address must be $coder_address" >&2
  exit 1
}
case "${WORKSPACE_IO_DEVICE:-}" in
  /dev/disk/by-uuid/*) ;;
  *) echo "WORKSPACE_IO_DEVICE must be a stable /dev/disk/by-uuid path" >&2; exit 1 ;;
esac
[ -b "$WORKSPACE_IO_DEVICE" ] || {
  echo "$WORKSPACE_IO_DEVICE must resolve to a block device" >&2
  exit 1
}
grep -qi microsoft /proc/sys/kernel/osrelease || {
  echo "owner_pc_beta requires WSL2" >&2
  exit 1
}
grep -q '^ID=ubuntu$' /etc/os-release &&
  grep -q '^VERSION_ID="24.04"$' /etc/os-release || {
    echo "owner_pc_beta requires Ubuntu 24.04" >&2
    exit 1
  }

[ -f "$image" ] && [ ! -L "$image" ] || {
  echo "$image must be a non-symlink regular file" >&2
  exit 1
}
[ "$(stat -c '%u:%g:%a:%h:%s' "$image")" = "0:0:600:1:$expected_bytes" ] || {
  echo "$image must be root:root mode 0600, single-linked, and exactly 64 GiB" >&2
  exit 1
}
allocated_bytes=$(( $(stat -c '%b' "$image") * 512 ))
[ "$allocated_bytes" -ge "$expected_bytes" ] || {
  echo "$image must be fully allocated rather than sparse" >&2
  exit 1
}
image_device=$(findmnt --noheadings --output SOURCE --target "$image" | tr -d '[:space:]')
[ -b "$image_device" ] || {
  echo "$image must reside on a Linux-native block filesystem" >&2
  exit 1
}
[ "$(stat -L -c '%t:%T' "$image_device")" = "$(stat -L -c '%t:%T' "$WORKSPACE_IO_DEVICE")" ] || {
  echo "WORKSPACE_IO_DEVICE does not back the owner-PC storage image" >&2
  exit 1
}

verify_mount() {
  target=$(findmnt --noheadings --output TARGET --target "$mount_point" | tr -d '[:space:]')
  filesystem=$(findmnt --noheadings --output FSTYPE --target "$mount_point" | tr -d '[:space:]')
  options=$(findmnt --noheadings --output OPTIONS --target "$mount_point" | tr -d '[:space:]')
  source=$(findmnt --noheadings --output SOURCE --target "$mount_point" | tr -d '[:space:]')
  [ "$target" = "$mount_point" ] && [ "$filesystem" = xfs ] || {
    echo "$mount_point must be its own XFS mount" >&2
    exit 1
  }
  case ",$options," in *,pquota,*|*,prjquota,*) ;; *) echo "project quotas are not enabled" >&2; exit 1 ;; esac
  case ",$options," in *,nodev,*) ;; *) echo "$mount_point must be nodev" >&2; exit 1 ;; esac
  case ",$options," in *,nosuid,*) ;; *) echo "$mount_point must be nosuid" >&2; exit 1 ;; esac
  case "$source" in /dev/loop[0-9]*) ;; *) echo "$mount_point is not loop-backed" >&2; exit 1 ;; esac
  backing=$(losetup --noheadings --output BACK-FILE "$source" | sed -e 's/[[:space:]]*$//')
  [ "$(realpath "$backing")" = "$image" ] || {
    echo "$source is attached to an unexpected backing file" >&2
    exit 1
  }
  state=$(xfs_quota -x -c 'state -p' "$mount_point")
  printf '%s\n' "$state" | grep -Eq 'Accounting:[[:space:]]+ON' &&
    printf '%s\n' "$state" | grep -Eq 'Enforcement:[[:space:]]+ON' || {
      echo "XFS project-quota accounting and enforcement must both be on" >&2
      exit 1
    }
}

ensure_network() {
  existing=$(ip -4 -o address show to "$coder_address/32" | awk '{print $2}')
  case "$existing" in
    "") ip address add "$coder_address/32" dev lo ;;
    lo) ;;
    *) echo "$coder_address already belongs to unexpected interface $existing" >&2; exit 1 ;;
  esac
}

start_runtime() {
  install -d -o root -g root -m 0755 "$mount_point"
  if findmnt --mountpoint "$mount_point" >/dev/null 2>&1; then
    verify_mount
  else
    loops=$(losetup --associated "$image" --noheadings --output NAME | awk 'NF')
    loop_count=$(printf '%s\n' "$loops" | awk 'NF {count++} END {print count+0}')
    [ "$loop_count" -le 1 ] || {
      echo "$image is attached to more than one loop device" >&2
      exit 1
    }
    created=false
    if [ "$loop_count" -eq 0 ]; then
      loop_device=$(losetup --find --show --nooverlap "$image")
      created=true
    else
      loop_device=$loops
    fi
    if ! mount -t xfs -o pquota,nodev,nosuid,noatime "$loop_device" "$mount_point"; then
      [ "$created" = false ] || losetup --detach "$loop_device"
      exit 1
    fi
    verify_mount
  fi

  getent passwd coder-provisioner >/dev/null || {
    echo "coder-provisioner account is missing" >&2
    exit 1
  }
  install -d -o 999 -g 999 -m 0700 "$mount_point/postgres"
  install -d -o 1000 -g 1000 -m 0700 "$mount_point/coder"
  install -d -o root -g root -m 0755 "$mount_point/caddy"
  install -d -o 1000 -g 1000 -m 0700 "$mount_point/caddy/data" "$mount_point/caddy/config"
  install -d -o root -g root -m 0711 "$mount_point/workspaces"
  install -d -o root -g root -m 0700 \
    "$mount_point/workspaces/.runtime-home" \
    "$mount_point/workspaces/.containers" \
    "$mount_point/workspaces/.networks"
  install -d -o coder-provisioner -g coder-provisioner -m 0700 \
    "$mount_point/workspaces/.provisioner-home"
  install -d -o root -g root -m 0555 "$mount_point/workspace-disk-probe"
  install -d -o root -g root -m 0711 "$mount_point/checkpoints"
  install -d -o 65532 -g 65532 -m 0700 "$mount_point/checkpoints/workspace-files"
  /usr/local/libexec/codex-mobile/prepare-workspace-overlay-quota
  ensure_network
}

stop_runtime() {
  if systemctl --quiet is-active codex-mobile-workspace-runtime.service; then
    echo "stop the workspace runtime before detaching owner-PC storage" >&2
    exit 1
  fi
  ip address del "$coder_address/32" dev lo 2>/dev/null || true
  if findmnt --mountpoint "$mount_point" >/dev/null 2>&1; then
    verify_mount
    overlay_root=$mount_point/workspaces/.containers/overlay
    volume_root=$mount_point/workspaces/.containers/volumes
    if findmnt --mountpoint "$overlay_root" >/dev/null 2>&1 ||
      findmnt --mountpoint "$volume_root" >/dev/null 2>&1; then
      /usr/local/libexec/codex-mobile/prepare-workspace-overlay-quota
      umount "$volume_root"
      umount "$overlay_root"
    fi
    source=$(findmnt --noheadings --output SOURCE --target "$mount_point" | tr -d '[:space:]')
    sync
    umount "$mount_point"
    losetup --detach "$source"
  fi
}

case "${1:-}" in
  start) start_runtime ;;
  stop) stop_runtime ;;
  verify) verify_mount; ensure_network ;;
  *) echo "usage: $0 start|stop|verify" >&2; exit 2 ;;
esac
